instance:
  alias:
    ActionFactory: "YouTrackPHP\Action\ActionFactory"
    ObjectCreator: "YouTrackPHP\Object\ObjectCreator"
    Client: "Guzzle\Http\Client"
  ObjectCreator:
    parameters:
      objectClasses:
        Issue: "YouTrackPHP\Object\Standard\Issue"
        IssueChange: "YouTrackPHP\Object\Standard\IssueChange"
        IssueChangeGroup: "YouTrackPHP\Object\Standard\IssueChangeGroup"
  Client:
    injections:
      setBaseUrl:
        url: "http://localhost:8080/rest"
      setDefaultHeaders:
        headers:
          Accept: "application/json"
  ActionFactory:
    parameters:
      client: "Client"
      objectCreator: "ObjectCreator"